### ISSUE TITLE
Don't use UUID for auth-token

### ISSUE THREAD

**Issue by pythoneer** [svenstaro/rust-web-boilerplate#9]
UUIDs do not hold up to the security requirements necessary for auth-tokens

https://github.com/svenstaro/rust-web-boilerplate/blob/master/src/models/user.rs#L53

**Comment by svenstaro** [comment]
I don't really see why. From what I can find on the web, uuid4 should be fine because they are meant to use proper random sources. Given that, they should not be any less secure than other 128 bit strings from /dev/urandom. Could you elaborate?

**Comment by pythoneer** [comment]
This is just a "general" advise that does not and should not depend on the implementation of UUID in use. Citing the [UUID RFC](https://tools.ietf.org/html/rfc4122#section-6)

> 6.  Security Considerations
> 
> Do not assume that UUIDs are hard to guess; they should not be used
   as security capabilities (identifiers whose mere possession grants
   access), for example.  A predictable random number source will
   exacerbate the situation.
> 
> Do not assume that it is easy to determine if a UUID has been
   slightly transposed in order to redirect a reference to another
   object.  Humans do not have the ability to easily check the integrity
   of a UUID by simply glancing at it.
> 
> Distributed applications generating UUIDs at a variety of hosts must
   be willing to rely on the random number source at all hosts.  If this
   is not feasible, the namespace variant should be used.

**Comment by svenstaro** [comment]
Alright, that is good enough for me. Will change this to something with entropy guarantees.

**Comment by pythoneer** [comment]
nice, just as a follow up [section 4.4](https://tools.ietf.org/html/rfc4122#section-4.4) talks about UUID version 4 in detail tl;dr not all bits are random

**Comment by svenstaro** [comment]
I changed this in f6c0f77, can you take a look whether this look ok to you?

**Comment by pythoneer** [comment]
LGTM, but i am no security expert!
